# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountDown' do
  use_frameworks!

  # Pods for CountDown
	pod 'SwiftLint'


  target 'CountDownTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountDownUITests' do
    # Pods for testing
  end

end
